In [5]:
from jax import vjp, jvp, jacfwd
import jax
import jax.numpy as jnp
import numpy as np

In [15]:
def f(x): #R3->R1
    return x[0]**3 + x[1]**2 + x[0] 

def dfdx_analytic(x):
    return jnp.array([3*x[0]**2, 2*x[1], 1])

def g(y, c): #R2->R3
    return c*jnp.array([jnp.sin(y[0]),  y[0]-y[1], y[1]**2])

def dgdx_analytic(y, c):
    return c*np.array([[jnp.cos(y[0]), 0], [1, -1], [0, 2*y[1]]])

In [24]:
c = 0.75
g_jax = lambda y: g(y, c)
dgdx_jax = lambda y: jacfwd(g_jax)(y)
dfdx_jax = lambda x: jacfwd(f)(x)

In [31]:
#f = lambda x: np.sum(3 * x ** 2)
y = jnp.array([1.,1.])
primal_value = g_jax(y)
tangent_vector = dgdx_jax(y)[:,0]
#tangent_vector = dfdx_jax(g_jax(y))
out, f_jvp = jax.jvp(f, (primal_value, ), (tangent_vector, ))
print(out, f_jvp)

0.88246626 0.8894216


In [32]:
f(g(y,c))

Array(0.88246626, dtype=float32)

In [33]:
dfdx_analytic(g(y,c)) 

Array([1.194874, 0.      , 1.      ], dtype=float32)

In [34]:
(dgdx_analytic(y, c))

array([[ 0.40522675,  0.        ],
       [ 0.75      , -0.75      ],
       [ 0.        ,  1.5       ]])

In [35]:
jnp.matmul(dfdx_analytic(g(y,c)), (dgdx_analytic(y, c)))

Array([0.48419493, 1.5       ], dtype=float32)

In [23]:
1.194874*0.40522675

0.4841949076795

In [162]:
tangent_vector

Array([0.4052267, 0.75     , 0.       ], dtype=float32)

In [176]:
g0.shape

(3,)

In [180]:
dg0.shape

(2, 3)

In [187]:
jax.vjp(f, g0)[0]

Array(0.88246626, dtype=float32)

In [190]:
vjp_fun = lambda x, v: jax.vjp(f, x)[1](v)[0]

x=jnp.array([1.,2,3])

g0 = g_jax(y)
df0 = jnp.transpose(dfdx_analytic(x))
# compute J^T v
vjp = vjp_fun(g0,df0)

In [191]:
vjp

Array([17.558992,  0.      ,  0.      ], dtype=float32)